import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Link from 'next/link';
import { Button } from '@/components/ui/button';
import { FileIcon, StarIcon } from 'lucide-react';
import { SideNav } from './side-nav';

const inter = Inter({ subsets: ['latin'] });

// export const metadata: Metadata = {
//   title: 'Files App',
//   description: 'Generated by @steezycreates',
// };

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className="container max-auto pt-12">
      <div className="flex gap-8">
        <SideNav />
        <div className="w-full">{children}</div>
      </div>
    </main>
  );
}
